table members_SIA
	lineageTag: d0eabb1a-f722-47ab-9063-b4a242064655

	column id
		dataType: int64
		formatString: 0
		lineageTag: beb83736-ba4e-48d0-bac0-ed76f8394bcf
		summarizeBy: sum
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column uri
		dataType: string
		lineageTag: 5d87e371-ac4d-456c-8bde-85859d2883ad
		summarizeBy: none
		sourceColumn: uri

		annotation SummarizationSetBy = Automatic

	column at_legal_entity_registration_number
		dataType: int64
		formatString: 0
		lineageTag: 7300490c-814a-493c-80dd-9df35fe73231
		summarizeBy: none
		sourceColumn: at_legal_entity_registration_number

		annotation SummarizationSetBy = Automatic

	column entity_type
		dataType: string
		lineageTag: 1f25618b-f12f-4d9f-9a1e-1fa7e51d49a9
		summarizeBy: none
		sourceColumn: entity_type

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: fc65cda4-d930-4f3d-b14d-95a35a04263b
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column latvian_identity_number_masked
		dataType: string
		lineageTag: f5228997-ffbc-4cc1-9a67-2fdd2df45bb9
		summarizeBy: none
		sourceColumn: latvian_identity_number_masked

		annotation SummarizationSetBy = Automatic

	column birth_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 71a107a5-2ea9-4056-bc09-8b5f9da817de
		summarizeBy: none
		sourceColumn: birth_date

		variation Variation
			isDefault
			relationship: fef7d29c-7611-4176-b148-f82bc81f20d2
			defaultHierarchy: LocalDateTable_50c0ea7c-7dd9-4c1e-ae5f-72c639d8bfef.'Datumu hierarhija'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column legal_entity_registration_number
		dataType: int64
		formatString: 0
		lineageTag: d7ff3828-5e2b-433e-86a8-bd4c3b01b1af
		summarizeBy: sum
		sourceColumn: legal_entity_registration_number

		annotation SummarizationSetBy = Automatic

	column number_of_shares
		dataType: string
		lineageTag: b98544f3-c50b-49a0-86bf-057c7014fd62
		summarizeBy: none
		sourceColumn: number_of_shares

		annotation SummarizationSetBy = Automatic

	column share_nominal_value
		dataType: string
		lineageTag: 2d000553-12cb-466b-9e42-4f9f5976d32e
		summarizeBy: none
		sourceColumn: share_nominal_value

		annotation SummarizationSetBy = Automatic

	column share_currency
		dataType: string
		lineageTag: 9cc3efaa-b517-4296-ad39-a948616f52a3
		summarizeBy: none
		sourceColumn: share_currency

		annotation SummarizationSetBy = Automatic

	column date_from
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7e4390ad-68e4-4df5-a0da-ccc81980c3be
		summarizeBy: none
		sourceColumn: date_from

		variation Variation
			isDefault
			relationship: a60302f3-35f9-4372-a6c6-0c63001108b7
			defaultHierarchy: LocalDateTable_0362a35d-61b5-43a8-90e0-1b89ffb4d60a.'Datumu hierarhija'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column registered_on
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2be2b3fd-f72b-4c00-9e33-fcf9f813894a
		summarizeBy: none
		sourceColumn: registered_on

		variation Variation
			isDefault
			relationship: 4f806bf8-034a-4bda-9a9b-987c44e62a59
			defaultHierarchy: LocalDateTable_f182aa79-f05c-4675-a886-8fc42e2b2287.'Datumu hierarhija'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column last_modified_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 4ea1da60-9521-4e70-ac8e-712f3a5d6b58
		summarizeBy: none
		sourceColumn: last_modified_at

		variation Variation
			isDefault
			relationship: ccbb5f25-d9ec-4618-91c9-b7753b9eedb0
			defaultHierarchy: LocalDateTable_5067c043-83e6-4bbc-8f69-db82707542b4.'Datumu hierarhija'

		annotation SummarizationSetBy = Automatic

	partition members_SIA = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://data.gov.lv/dati/dataset/e1162626-e02a-4545-9236-37553609a988/resource/837b451a-4833-4fd1-bfdd-b45b35a994fd/download/members.csv"),[Delimiter=";", Columns=14, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"id", Int64.Type}, {"uri", type text}, {"at_legal_entity_registration_number", Int64.Type}, {"entity_type", type text}, {"name", type text}, {"latvian_identity_number_masked", type text}, {"birth_date", type date}, {"legal_entity_registration_number", Int64.Type}, {"number_of_shares", type text}, {"share_nominal_value", type text}, {"share_currency", type text}, {"date_from", type date}, {"registered_on", type date}, {"last_modified_at", type datetime}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

