table 'ur_database register'
	lineageTag: 63ac4757-e8ab-4129-b9ac-78a90a5eab89

	column regcode
		dataType: int64
		formatString: 0
		lineageTag: 7132f02e-3762-4f17-bb64-5e1afce4071d
		summarizeBy: none
		sourceColumn: regcode

		annotation SummarizationSetBy = Automatic

	column sepa
		dataType: string
		lineageTag: e3140aed-7e4f-4df5-b2e7-f78bb959278d
		summarizeBy: none
		sourceColumn: sepa

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: ca6aec40-8747-4887-9cd1-0eef56df0a46
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column name_before_quotes
		dataType: string
		lineageTag: 5aebd97f-58a6-49d2-ba84-9ea3fc1463d2
		summarizeBy: none
		sourceColumn: name_before_quotes

		annotation SummarizationSetBy = Automatic

	column name_in_quotes
		dataType: string
		lineageTag: 6b36f70a-4e90-4e8f-8d33-f2da926c5501
		summarizeBy: none
		sourceColumn: name_in_quotes

		annotation SummarizationSetBy = Automatic

	column name_after_quotes
		dataType: string
		lineageTag: d3bac91b-bd9e-409d-b49f-733a514d9815
		summarizeBy: none
		sourceColumn: name_after_quotes

		annotation SummarizationSetBy = Automatic

	column without_quotes
		dataType: int64
		lineageTag: c6d73524-3a17-43e9-a3a2-09c81fa24711
		summarizeBy: sum
		sourceColumn: without_quotes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column regtype
		dataType: string
		lineageTag: 2793b5be-5991-4b17-9c4e-e582af89e5d3
		summarizeBy: none
		sourceColumn: regtype

		annotation SummarizationSetBy = Automatic

	column regtype_text
		dataType: string
		lineageTag: 01272554-69a7-478e-920f-344e23d2aec8
		summarizeBy: none
		sourceColumn: regtype_text

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: 8fced5ca-a4ce-48fb-a7a9-dd82859eca15
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column type_text
		dataType: string
		lineageTag: 525c17b0-0e04-42b4-b906-1310308b415d
		summarizeBy: none
		sourceColumn: type_text

		annotation SummarizationSetBy = Automatic

	column registered
		dataType: dateTime
		formatString: Long Date
		lineageTag: 427bc824-a634-4598-ae98-431fd56cb385
		summarizeBy: none
		sourceColumn: registered

		variation Variation
			isDefault
			relationship: 4d3bf661-2071-48f2-a5f8-07264079b7a5
			defaultHierarchy: LocalDateTable_4d9e96cc-8dc0-4769-b18d-8d0a7ebb5261.'Datumu hierarhija'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column terminated
		dataType: dateTime
		formatString: Long Date
		lineageTag: 14c2da29-1d59-49fb-91f9-3c39eece3a61
		summarizeBy: none
		sourceColumn: terminated

		variation Variation
			isDefault
			relationship: 3d274a5b-7a73-43c3-add8-175e15a327c5
			defaultHierarchy: LocalDateTable_b9c56779-9f18-4c12-91ec-390b2c996c6d.'Datumu hierarhija'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column closed
		dataType: string
		lineageTag: 21eda5f7-d97d-4846-9c07-b1f572bddf5b
		summarizeBy: none
		sourceColumn: closed

		annotation SummarizationSetBy = Automatic

	column address
		dataType: string
		lineageTag: 96c1a99f-73bf-4e87-9994-f0d5a0f8a383
		summarizeBy: none
		sourceColumn: address

		annotation SummarizationSetBy = Automatic

	column index
		dataType: int64
		lineageTag: bf92b1bd-bcb2-4699-86c5-f3e20a2f221b
		summarizeBy: sum
		sourceColumn: index

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column addressid
		dataType: int64
		formatString: 0
		lineageTag: 38cca99d-0d9e-4962-8eaf-a3457862f29d
		summarizeBy: sum
		sourceColumn: addressid

		annotation SummarizationSetBy = Automatic

	column region
		dataType: int64
		formatString: 0
		lineageTag: fc246286-cd04-4cd5-8435-a1299647800b
		summarizeBy: sum
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column city
		dataType: int64
		lineageTag: 1119ef33-e917-4049-8b63-d7aefb425cb1
		summarizeBy: sum
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column atvk
		dataType: int64
		lineageTag: 611fd857-43a6-4ebf-a58f-f6b44fde8e14
		summarizeBy: sum
		sourceColumn: atvk

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column reregistration_term
		dataType: string
		lineageTag: cc97051a-4442-4414-813c-38ca3a433e9d
		summarizeBy: none
		sourceColumn: reregistration_term

		annotation SummarizationSetBy = Automatic

	partition 'ur_database register-e5ac7734-beab-4193-8ba4-76c6cb855071' = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://data.gov.lv/dati/dataset/4de9697f-850b-45ec-8bba-61fa09ce932f/resource/25e80bf3-f107-4ab4-89ef-251b5b9374e9/download/register.csv"),[Delimiter=";", Columns=21, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"regcode", Int64.Type}, {"sepa", type text}, {"name", type text}, {"name_before_quotes", type text}, {"name_in_quotes", type text}, {"name_after_quotes", type text}, {"without_quotes", Int64.Type}, {"regtype", type text}, {"regtype_text", type text}, {"type", type text}, {"type_text", type text}, {"registered", type date}, {"terminated", type date}, {"closed", type text}, {"address", type text}, {"index", Int64.Type}, {"addressid", Int64.Type}, {"region", Int64.Type}, {"city", Int64.Type}, {"atvk", Int64.Type}, {"reregistration_term", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

