table 'ur_database balance_sheets'
	lineageTag: aec552e1-581c-4200-9a69-a4d2130fb3d2

	column statement_id
		dataType: int64
		formatString: 0
		lineageTag: c54fbb6f-dd26-418e-9b8a-a3b0c33042ff
		summarizeBy: none
		sourceColumn: statement_id

		annotation SummarizationSetBy = Automatic

	column file_id
		dataType: int64
		formatString: 0
		lineageTag: cd7ef9e6-84a5-4d7b-9c96-0e131cab602f
		summarizeBy: sum
		sourceColumn: file_id

		annotation SummarizationSetBy = Automatic

	column cash
		dataType: int64
		formatString: 0
		lineageTag: 8f201558-d4b0-417d-a7a9-95857de6cc20
		summarizeBy: sum
		sourceColumn: cash

		annotation SummarizationSetBy = Automatic

	column marketable_securities
		dataType: int64
		formatString: 0
		lineageTag: 43f8c313-ea96-4cb2-ba28-26821338549b
		summarizeBy: sum
		sourceColumn: marketable_securities

		annotation SummarizationSetBy = Automatic

	column accounts_receivable
		dataType: int64
		formatString: #,0
		lineageTag: 48af12b9-2869-44f5-ab59-7d0863b3a63e
		summarizeBy: sum
		sourceColumn: accounts_receivable

		annotation SummarizationSetBy = Automatic

	column inventories
		dataType: int64
		formatString: 0
		lineageTag: 57e2f3c4-82b6-4cdb-a340-2433040203f6
		summarizeBy: sum
		sourceColumn: inventories

		annotation SummarizationSetBy = Automatic

	column total_current_assets
		dataType: int64
		formatString: 0
		lineageTag: 6abaeddb-69a6-4528-bade-a0d736d93e11
		summarizeBy: sum
		sourceColumn: total_current_assets

		annotation SummarizationSetBy = Automatic

	column investments
		dataType: int64
		formatString: 0
		lineageTag: 3c97038a-a855-48a2-bb3a-a6fe4c707f45
		summarizeBy: sum
		sourceColumn: investments

		annotation SummarizationSetBy = Automatic

	column fixed_assets
		dataType: int64
		formatString: 0
		lineageTag: 6b5d17dd-8909-4ccd-bf13-dbec099042ff
		summarizeBy: sum
		sourceColumn: fixed_assets

		annotation SummarizationSetBy = Automatic

	column intangible_assets
		dataType: int64
		formatString: 0
		lineageTag: 328849f8-b3b3-41fc-8c5f-b743ded3a1a0
		summarizeBy: sum
		sourceColumn: intangible_assets

		annotation SummarizationSetBy = Automatic

	column total_non_current_assets
		dataType: int64
		formatString: 0
		lineageTag: 4415cda2-8d7c-4227-97cb-644a9b282177
		summarizeBy: sum
		sourceColumn: total_non_current_assets

		annotation SummarizationSetBy = Automatic

	column total_assets
		dataType: int64
		formatString: 0
		lineageTag: 5e384756-63d3-4be6-a83b-5a46109a8bbc
		summarizeBy: sum
		sourceColumn: total_assets

		annotation SummarizationSetBy = Automatic

	column future_housing_repairs_payments
		dataType: string
		lineageTag: 89db3316-3c3e-46bd-8c5e-d8440b99df5d
		summarizeBy: none
		sourceColumn: future_housing_repairs_payments

		annotation SummarizationSetBy = Automatic

	column current_liabilities
		dataType: int64
		formatString: 0
		lineageTag: 02f704b3-06a7-4919-a0de-9706190b4768
		summarizeBy: sum
		sourceColumn: current_liabilities

		annotation SummarizationSetBy = Automatic

	column non_current_liabilities
		dataType: int64
		formatString: 0
		lineageTag: c82707cb-0f7d-4640-8062-71a4119dcf06
		summarizeBy: sum
		sourceColumn: non_current_liabilities

		annotation SummarizationSetBy = Automatic

	column provisions
		dataType: int64
		lineageTag: 35850127-c206-4838-8024-bb26b2901924
		summarizeBy: sum
		sourceColumn: provisions

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column equity
		dataType: int64
		formatString: 0
		lineageTag: 4bebb691-02c2-4616-bf47-c114bb79aa03
		summarizeBy: sum
		sourceColumn: equity

		annotation SummarizationSetBy = Automatic

	column total_equities
		dataType: int64
		formatString: 0
		lineageTag: f0dea107-4ae2-41ce-9664-ad99e98e87a6
		summarizeBy: sum
		sourceColumn: total_equities

		annotation SummarizationSetBy = Automatic

	partition 'ur_database balance_sheets-c1a9d2f1-2900-4f2b-ba07-a8e9830d8e05' = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://data.gov.lv/dati/dataset/8d31b878-536a-44aa-a013-8bc6b669d477/resource/50ef4f26-f410-4007-b296-22043ca3dc43/download/balance_sheets.csv"),[Delimiter=";", Columns=18, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"statement_id", Int64.Type}, {"file_id", Int64.Type}, {"cash", Int64.Type}, {"marketable_securities", Int64.Type}, {"accounts_receivable", Int64.Type}, {"inventories", Int64.Type}, {"total_current_assets", Int64.Type}, {"investments", Int64.Type}, {"fixed_assets", Int64.Type}, {"intangible_assets", Int64.Type}, {"total_non_current_assets", Int64.Type}, {"total_assets", Int64.Type}, {"future_housing_repairs_payments", type text}, {"current_liabilities", Int64.Type}, {"non_current_liabilities", Int64.Type}, {"provisions", Int64.Type}, {"equity", Int64.Type}, {"total_equities", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

