table 'ur_database financial_statements'
	lineageTag: 401c00d9-de7a-49ef-ac8b-1b014b802f57

	column id
		dataType: int64
		formatString: 0
		lineageTag: 9e38ea20-5bdb-4238-a6a2-41e71f6cf6d2
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column file_id
		dataType: int64
		formatString: 0
		lineageTag: 0d6573b7-2171-47c4-a95b-4e26bf6b5027
		summarizeBy: sum
		sourceColumn: file_id

		annotation SummarizationSetBy = Automatic

	column legal_entity_registration_number
		dataType: int64
		formatString: 0
		lineageTag: 4332ed52-b36f-4a64-a131-a2af4af94600
		summarizeBy: none
		sourceColumn: legal_entity_registration_number

		annotation SummarizationSetBy = Automatic

	column source_schema
		dataType: string
		lineageTag: 3e7ee80b-fc0a-4acc-a090-bb22bc4d23d2
		summarizeBy: none
		sourceColumn: source_schema

		annotation SummarizationSetBy = Automatic

	column source_type
		dataType: string
		lineageTag: 42e11d20-876f-4d48-b49d-4277f28b3c93
		summarizeBy: none
		sourceColumn: source_type

		annotation SummarizationSetBy = Automatic

	column year
		dataType: int64
		formatString: 0
		lineageTag: 10a0d1aa-19d4-4780-848f-854ac5357640
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column year_started_on
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5648c19e-9466-4933-bf7c-a39bba74a06a
		summarizeBy: none
		sourceColumn: year_started_on

		variation Variation
			isDefault
			relationship: c5304cd3-ac20-43f2-96b6-19e2729a7999
			defaultHierarchy: LocalDateTable_abc63066-1226-4334-957c-72feab7fc581.'Datumu hierarhija'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column year_ended_on
		dataType: dateTime
		formatString: Long Date
		lineageTag: d4cde0b5-8d39-469c-9498-2f0d12464c3f
		summarizeBy: none
		sourceColumn: year_ended_on

		variation Variation
			isDefault
			relationship: 7eee8b8c-c93f-46eb-a0e5-a4abb1be1913
			defaultHierarchy: LocalDateTable_901bee32-ac08-4596-a50a-4d9f42501068.'Datumu hierarhija'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column employees
		dataType: int64
		formatString: 0
		lineageTag: 21ca9a1d-935b-412e-bb0f-339b44bfc331
		summarizeBy: sum
		sourceColumn: employees

		annotation SummarizationSetBy = Automatic

	column rounded_to_nearest
		dataType: string
		lineageTag: f17185a6-cb2e-4085-a370-b79dc4256651
		summarizeBy: none
		sourceColumn: rounded_to_nearest

		annotation SummarizationSetBy = Automatic

	column currency
		dataType: string
		lineageTag: 62528a91-01bc-48b0-9821-85efe62d85e9
		summarizeBy: none
		sourceColumn: currency

		annotation SummarizationSetBy = Automatic

	column created_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 3cfb5cee-65a5-4a56-b1a9-965e142887ee
		summarizeBy: none
		sourceColumn: created_at

		variation Variation
			isDefault
			relationship: a988e9ea-ceca-41dd-8e73-357f271f35e5
			defaultHierarchy: LocalDateTable_8daf33ce-4b16-45c8-bfb5-85f4f8471c5a.'Datumu hierarhija'

		annotation SummarizationSetBy = Automatic

	partition 'ur_database financial_statements-181bc11f-8140-4a3d-9a53-6392d822b071' = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://data.gov.lv/dati/dataset/8d31b878-536a-44aa-a013-8bc6b669d477/resource/27fcc5ec-c63b-4bfd-bb08-01f073a52d04/download/financial_statements.csv"),[Delimiter=";", Columns=12, Encoding=1257, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"id", Int64.Type}, {"file_id", Int64.Type}, {"legal_entity_registration_number", Int64.Type}, {"source_schema", type text}, {"source_type", type text}, {"year", Int64.Type}, {"year_started_on", type date}, {"year_ended_on", type date}, {"employees", Int64.Type}, {"rounded_to_nearest", type text}, {"currency", type text}, {"created_at", type datetime}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

